#!/usr/bin/env python

import psana

psana.setConfigFile('/reg/neh/home2/tjlane/opt/trapdoor/hitfinding/hitfinder.cfg')
psana.setOption('psana.l3t-accept-only',0)

ds = psana.DataSource('shmem=4_8_psana_CXI.0:stop=no')
ds1_src = psana.Source('DetInfo(CxiDs1.0:Cspad.0)')

for evt in ds.events():

    pass
    #print 'shot'
    #print evt.keys()
    #print evt.get(psana.None, ds1_src, 'peaks')
    #break
    

