#!/usr/bin/env python

from trapdoor import guardian

camera_name           = 'CxiDs1.0:Cspad.0'
adu_threshold         = 5000
consecutive_threshold = 5
area_threshold        = 30

guardian.main(camera_name, adu_threshold, consecutive_threshold, area_threshold)


